### ISSUE TITLE
New Platform conf to provide TLS materials by host, allowing multiple users

### ISSUE THREAD

**Issue by KaioKei** [LCailliot/easyssl#7]
# Feature

Depends on #6

example :

```yaml
platform:
  password: "secret123"
  hosts:
    - hostname: server1 # affects filename, SAN and CN
      ip: 172.28.128.21 # affects SAN
    - users: ["admin"] # Optional, affects filenames and CN
      hostname: server2 # affects SAN
      ip: 172.28.128.22 # affects SAN
    - cn: server2 # Optional, affects CN
      users: ["admin-1", "admin-2"] # Optional, affects filenames
      hostname: server3 # affects SAN
      ip: 172.28.128.22 # affects SAN

```

## Todo

* [x] generate TLS material per host, or one TLS material per users' on each host
* [x] certificates' SAN is `DNS:${hostname} IP:${ip_conf}`
* [x] certificates' CN is `${hostname}`
* [x] `users` conf: 
  * [x] Optional, the default name is the hostname 
  * [x] The names affect the generated files. Example, if name is `bob`, the generated private key is `bob.p8`
  * [x] The names affect the CN value like `${user}`
* [x] `cn` conf:
  * [x] Optional, the default value is the hostname, or `{user}` if usernames are provided 
* [x] extract the TLS material of each user of a node inside the same folder
